sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: uGtgXpeV/LD2P07ZemtZn80ee5iVabvcmFp+08ORGmEe6+HkzwOXHfqb+wbxFuxKOQNqpmcRjWwDW4wmPkTrxAVivqZu/m1K35WhDPMZ4whz7KxO0VHmWO/190k6GqrEapeeLwfLkz84QL2bmteHsADTyJKG6U4jZslylITEmGdraxJAwv+CxfZvapE83EvokUXpyliyIMY/x12+DU9tY+PXale4NhUlcpW9QfuhWQL5h55/+EWNLh1brkKrtdkN47hw0eX5kDmJt4LlYbdTdCvthCcvKq6ivrGNmXcudKvShd1+UjcV05vqhSObkPV+mfJlYH8BwDN8MOJPvmD5P/DCg4mmFJEO4+JKxx8ekXtOH0m/WalitL3Q4Qs93bRrQ1UurtJ0vDMmWnflDUscp+mCoruWNrSMOZil9nO4+OAKPTH2Mb3m8GzrSUG2zs+oXmWSg+3XlS64yG4WPhSDmD/d87Y3q677R4fwZ4UMIDMDMVlDk8uxvqB1VXLIOwfmpamDllPRJO0sKW0oP47RsZWpygv5bDzqUuNeskRIcRF3BXX2ynEPoMEHUjbF2bj2U5BMuYrVwkCkclq0e5kZZJYfeHT7rWiiAiHU3fv9Ex/1G4iIzkfpQrPsakrFVvJm4CjBIIiGzItV10jA/h1hRBVf3F5RRWJ8c/raTNwrYdY=
  - secure: XFwU2S1GvjqzYhinCU7BHqEziFtOiMWSv2yjOxZ9PKc9tgLmrSalj0MvaAyjXtPurL35NzAJYOruLUHuShW7hoF5ITlyPw5iHUj1plAFmY0WUnCd4QfPtdSQNlXmA+eToNFJ1LsDUKy0NUzdgiO90dPPmq8V/LwwxXuiZmBuaxovTUKMSXqAcV3olnMZ3LkNLCGMzcbyVPwHb9bo6iDplIs76B4Rk+y/dd9Og/houM8Ajp5Z6/oqFV8dwcHGbOMseavuVkHe3a6qR8OtwKbCI3uyioodeKadGNubu/nQ3fdBlNsf6qHUHUdZkTi6llZ1YcfTZUR0GJ0x4b9+MyO0V6enDMt4chpGYi0jIA+sNl1ddgXGfXfVJIhsuouuZ5l2jNbBOUogjlvUtNE6fjb9+t8fdUtsdhn7MIjJs8KehkHS+77irhMKvK1GyqKRSO2+z99xHUlnpZCCpOvsvfxy/MAtbMKBedh0gC5FKMPmw/rwCC4nucTN/ip1vuaQo+AM/COzmBjfF8WEPJYHVZCUxUN+EVQ+c2Pfv/Bgz9tQ2JeCI9o9J9w/lBY2XPX3F0XAtKn1qVch5MvP2gbfAxM0g8D1oC6ANtx1nmlQTPVCD4LIITvsZPebelHThYxCRk228OOilNarE5Gtu6rPgvWfqJcu3oXD3OFnakv359OTVVU=
